// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAT71Fgd23GYa92bH0nKERPRQ4_4uJFro',
    appId: '1:887693328316:android:fbe33dee39284621b4b5b9',
    messagingSenderId: '887693328316',
    projectId: 'auth-app-7c15f',
    storageBucket: 'auth-app-7c15f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6hFciyAbSqdisAKML7zI5XntlQShwxmc',
    appId: '1:887693328316:ios:f237709e69392e6eb4b5b9',
    messagingSenderId: '887693328316',
    projectId: 'auth-app-7c15f',
    storageBucket: 'auth-app-7c15f.appspot.com',
    iosBundleId: 'com.example.task1Intern2grow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6hFciyAbSqdisAKML7zI5XntlQShwxmc',
    appId: '1:887693328316:ios:f237709e69392e6eb4b5b9',
    messagingSenderId: '887693328316',
    projectId: 'auth-app-7c15f',
    storageBucket: 'auth-app-7c15f.appspot.com',
    iosBundleId: 'com.example.task1Intern2grow',
  );
}
